CREATE TABLE EMPLOYEES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50),
    SALARY INT
);

INSERT INTO EMPLOYEES (NAME, SALARY) VALUES
('Ramesh', 1000),
('Santosh', 2000),
('Manish', 3000),
('Rahul', 4000),
('Rohit', 5000);

SELECT * FROM EMPLOYEES;

UPDATE EMPLOYEES
SET SALARY = 6000
WHERE NAME = 'Ramesh';

DELETE FROM EMPLOYEES
WHERE NAME = 'Rohit';


